WIZARD = 14
JESTER = 0

RED = '🔴'
BLUE = '🔵'
GREEN = '🟢'
YELLOW = '🟡'
SUIT_ORDER = [RED,BLUE,GREEN,YELLOW]

DETERMINE_TRUMP = 'determine_trump'
GUESS = 'guess'
PLAY = 'play'
GAME_PHASES = [DETERMINE_TRUMP, GUESS, PLAY]

MAX_ROUNDS = 2